name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt 3 application
        run: npm run generate # Static output for Pages

      - name: Install Wrangler v4 (avoid deprecated v2)
        run: npm install -g wrangler@latest

      - name: Verify output directory
        run: |
          ls -la dist || echo "ERROR: dist not found!"
          [ -d "dist" ] || exit 1

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: "rila"
          directory: "dist"
